[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rusty-os.json"

#[target.'cfg(target_os = "none")']
#runner = "bootimage runner"

[alias]
kbuild = """build --target x86_64-blog_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kcheck = """check --target x86_64-blog_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kdoc = """doc --target x86_64-blog_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
kclippy = """clippy --target x86_64-blog_os.json -Z build-std=core \
    -Z build-std-features=compiler-builtins-mem"""
